# base / production
services:

  pusher:
    container_name: laiive-pusher
    build:
      context: ./services
      dockerfile: pusher/Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env

  retriever:
    container_name: laiive-retriever
    build:
      context: ./services
      dockerfile: retriever/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
