# base / production
services:

  pusher:
    container_name: laiive-pusher
    build: ./services/pusher
    ports:
      - "8003:8003"
    env_file:
      - .env

  retriever:
    container_name: laiive-retriever
    build: ./services/retriever
    ports:
      - "8002:8002"
    env_file:
      - .env
