"""
Prompt registry package.
"""

from .prompts import (
    CLASSIFIER_PROMPT_VERSION,
    CLASSIFIER_SYSTEM_PROMPT,
    COMPOSER_PROMPT_VERSION,
    COMPOSER_SYSTEM_PROMPT,
    QUERY_BUILDER_PROMPT,
    QUERY_BUILDER_PROMPT_VERSION,
)

__all__ = [
    "CLASSIFIER_SYSTEM_PROMPT",
    "CLASSIFIER_PROMPT_VERSION",
    "COMPOSER_SYSTEM_PROMPT",
    "COMPOSER_PROMPT_VERSION",
    "QUERY_BUILDER_PROMPT",
    "QUERY_BUILDER_PROMPT_VERSION",
]
