"""
Prompt registry package.
"""
from .prompts import (
    DECISION_PROMPT,
    REACT_SYSTEM_PROMPT,
    OUT_OF_SCOPE_PROMPT,
    UNSAFE_CONTENT_PROMPT,
    QUERY_BUILDER_PROMPT,
    SAFETY_GUARD_PROMPT,
)

__all__ = [
    "DECISION_PROMPT",
    "REACT_SYSTEM_PROMPT",
    "OUT_OF_SCOPE_PROMPT",
    "UNSAFE_CONTENT_PROMPT",
    "QUERY_BUILDER_PROMPT",
    "SAFETY_GUARD_PROMPT",
]
